version: "3.7"
services:
  web:
    build: .
    environment:
      MYENV: venv
    volumes:
      - .:/code
    command: bash -c "
        python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    image: theripson/djangoproject:web
