version: "2"
services: 
  django-apache2:
    build: .
    image: theripson/djangoproject:deploy
    container_name: django-deploy
    ports:
      - '8005:80'
      - '3501:3500'
      - '4701:81'
    volumes: 
      - $PWD:/code
