version: "3.7"
services:
  web:
    build: .
    environment:
      MYENV: venv
    volumes:
      - .:/code
    image: theripson/djangoproject:web
  web_migrate:
    extends:
      service: web
    command: python manage.py migrate
    image: theripson/djangoproject:migrate
  web_run:
    extends:
      service: web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    image: theripson/djangoproject:run