# Generated by Django 4.0.5 on 2022-06-11 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.PositiveSmallIntegerField(help_text='czas podany w minutach')),
                ('image', models.ImageField(blank=True, upload_to='attractions_images/')),
                ('price', models.PositiveIntegerField(default=0)),
                ('desc', models.TextField()),
                ('lat', models.FloatField(default=0)),
                ('long', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='attractions_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('completed', models.BooleanField()),
                ('distance', models.CharField(blank=True, max_length=1000, null=True)),
                ('attractions', models.ManyToManyField(blank=True, to='main.attractions')),
                ('first_attraction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_attraction', to='main.attractions')),
                ('last_attraction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_attraction', to='main.attractions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attractions',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AddField(
            model_name='attractions',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.city'),
        ),
    ]
