# Generated by Django 4.0.5 on 2022-06-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_attractions_image_alter_city_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/attractions_images'),
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/attractions_images'),
        ),
    ]
